name = "Unixmatica"
author = "Aproxia"
version = "latest"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afcb050440fc68174f65324a948f717ab5930419114436b7aafc6e8ed7e0119c"

[versions]
fabric = "0.15.2"
minecraft = "1.20.1"
