name = "Unixmatica"
author = "Aproxia"
version = "latest"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "003c1d5b5f3bee6b12edb044164487db5614ae7181cf8890e45427ee2d08cd03"

[versions]
fabric = "0.15.2"
minecraft = "1.20.1"
